ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-base-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.image_tag_suffix if "image_tag_suffix" in cuda }}

LABEL maintainer "NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"

{% if "libraries_dev" in cuda.components %}
  {% set libraries_component_version = cuda.version.major + "-" + cuda.version.minor + "-" + cuda.components.libraries_dev.version %}
{% endif %}
{% if "libnpp" in cuda.components %}
  {% set libnpp_component_version = cuda.version.major + "-" + cuda.version.minor + "-" + cuda.components.libnpp.version %}
{% endif %}
{% if "nvtx" in cuda.components %}
  {% set nvtx_component_version = cuda.version.major + "-" + cuda.version.minor + "-" + cuda.components.nvtx.version %}
{% endif %}
{% if "libcublas" in cuda.components %}
  {% set libcublas_component_version = cuda.version.major + "-" + cuda.version.minor + "-" + cuda.components.libcublas.version %}
{% endif %}
{% if "libnccl2" in cuda.components %}
  {% set libnccl2_component_version = cuda.components.libnccl2.version + "+cuda" + cuda.version.major + "." + cuda.version.minor %}
ENV NCCL_VERSION {{ cuda.components.libnccl2.version[:-2] }}

{% endif -%}

RUN yum install -y \
    cuda-libraries-{{ libraries_component_version if libraries_component_version else "$CUDA_PKG_VERSION" }} \
    {% if cuda.version.major | int == 9 and cuda.version.minor | int == 0 %}
    cuda-cublas-{{ cuda.version.major }}-{{ cuda.version.minor }}={{ cuda.version.full }}.4-1 \
    {% endif %}
    {% if (cuda.version.major | int == 9 and cuda.version.minor | int == 2) or cuda.version.major | int >= 10 %}
    cuda-nvtx-{{ nvtx_component_version if cuda.version.major | int == 11 else "$CUDA_PKG_VERSION" }} \
    {% endif %}
    {% if cuda.version.major | int == 10 and cuda.version.minor | int >= 1 %}
    cuda-npp-{{ libnpp_component_version if libnpp_component_version else "$CUDA_PKG_VERSION" }} \
    libcublas10-{{ libcublas_component_version[5:] }} \
    {% elif cuda.version.major | int > 10 %}
    libnpp-{{ libnpp_component_version if libnpp_component_version else "$CUDA_PKG_VERSION" }} \
    libcublas-{{ libcublas_component_version }} \
    {% endif %}
    {% if libnccl2_component_version and "libnccl2" in cuda.components and "source" not in cuda.components.libnccl2 %}
    libnccl-{{ libnccl2_component_version }} \
    {% endif %}
    && yum clean all \
    && rm -rf /var/cache/yum/*

{% if "libnccl2" in cuda.components and "source" in cuda.components.libnccl2 %}
    {% set arch = cuda.arch %}
    {% if cuda.arch == "arm64" %} {% set arch = "aarch64" %} {% endif %}
    {% set basename =  "nccl_" + cuda.components.libnccl2.version + "-1+cuda" + cuda.version.major + "." + cuda.version.minor + "_" + arch + ".txz" %}
RUN yum install -y xz && NCCL_DOWNLOAD_SUM={{ cuda.components.libnccl2.sha256sum }} \
    && curl -fsSL {{ cuda.components.libnccl2.source }} -O \
    && echo "$NCCL_DOWNLOAD_SUM  {{ basename }}" | sha256sum -c - \
    && unxz {{ basename }} \
    && tar --no-same-owner --keep-old-files --no-overwrite-dir -xvf {{ basename[:-4] + ".tar" }} -C /usr/local/cuda/lib64/ --strip-components=2 --wildcards '*/lib/libnccl.so.*' \
    && tar --no-same-owner --keep-old-files --no-overwrite-dir -xvf  {{ basename[:-4] + ".tar" }} -C /usr/lib64/pkgconfig/ --strip-components=3 --wildcards '*/lib/pkgconfig/*' \
    && rm -f {{ basename[:-4] + ".tar" }} \
    && ldconfig
    && yum clean all \
    && rm -rf /var/cache/yum/*
{% endif %}
