ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-{{ cuda.cudnn.target }}-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.image_tag_suffix }}
LABEL maintainer "NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"

{% set cudnn_version = cuda.cudnn.version %}
{% if "-" in cuda.cudnn.version %}
  {% set cudnn_version = cuda.cudnn.version[:-2] %}
{% endif -%}

ENV CUDNN_VERSION {{ cudnn_version }}
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

{# {% if not cuda.cudnn.version.startswith("7.6") -%} #}
{#   {% set cudnn_version = cuda.cudnn.version[:3] -%} #}
{% if "-" in cuda.cudnn.version %}
  {% set cudnn_version = cuda.cudnn.version[:-2] %}
{% endif -%}

{% set iz_dev = "" %}
{% if cuda.cudnn.target == "devel" -%}
  {% set iz_dev = "-devel" %}
{% endif %}
{% if "source" in cuda.cudnn and cuda.cudnn.source %}
RUN CUDNN_DOWNLOAD_SUM={{ cuda.cudnn.sha256sum }} && \
    curl -fsSL {{ cuda.cudnn.source }} -O && \
  {% set basename = cuda.cudnn.basename %}
    echo "$CUDNN_DOWNLOAD_SUM  {{ basename }}" | sha256sum -c - && \
    rpm -vih {{ basename }} && \
    rm -f {{ basename }} && \
    ldconfig
  {% if cuda.cudnn.target == "devel" %}

RUN CUDNN_DOWNLOAD_SUM={{ cuda.cudnn.dev.sha256sum }} && \
    curl -fsSL {{ cuda.cudnn.dev.source }} -O && \
    {% set basename = cuda.cudnn.dev.basename %}
    echo "$CUDNN_DOWNLOAD_SUM  {{ basename }}" | sha256sum -c - && \
    rpm -vih {{ basename }} && \
    rm -f {{ basename }} && \
    ldconfig
  {% endif %}
{% elif "sha256sum" not in cuda.cudnn %}
RUN yum install -y \
    libcudnn{{ cuda.cudnn.version[0] }}{{ iz_dev }}-${CUDNN_VERSION}-1.cuda{{ cuda.version.major }}.{{ cuda.version.minor }} \
    && yum clean all \
    && rm -rf /var/cache/yum/*
{% else %}
  {% set arch = cuda.arch | replace("86_", "") %}
  {% set archive_path = "cuda/lib64/libcudnn.so.*" %}
  {% if arch == "ppc64le" %}
      {% set archive_path = "cuda/targets/ppc64le-linux/lib/libcudnn.so.*" %}
  {% endif %}
# cuDNN license: https://developer.nvidia.com/cudnn/license_agreement
RUN CUDNN_DOWNLOAD_SUM={{ cuda.cudnn.sha256sum }} && \
    curl -fsSL http://developer.download.nvidia.com/compute/redist/cudnn/v{{ cuda.cudnn.version[:cuda.cudnn.version.rfind(".")] }}/cudnn-{{ cuda.version.major }}.{{ cuda.version.minor }}-linux-{{ arch }}-v{{ cudnn_version }}.tgz -O && \
    echo "$CUDNN_DOWNLOAD_SUM  cudnn-{{ cuda.version.major }}.{{ cuda.version.minor }}-linux-{{ arch }}-v{{ cudnn_version}}.tgz" | sha256sum -c - && \
    tar --no-same-owner -xzf cudnn-{{ cuda.version.major }}.{{ cuda.version.minor }}-linux-{{ arch }}-v{{ cudnn_version }}.tgz -C /usr/local {% if cuda.cudnn.target == "runtime" -%}--wildcards '{{ archive_path }}' {% endif -%} && \
    rm cudnn-{{ cuda.version.major }}.{{ cuda.version.minor }}-linux-{{ arch }}-v{{ cudnn_version }}.tgz && \
    ldconfig
{% endif %}
