ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-runtime-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.image_tag_suffix if "image_tag_suffix" in cuda }}

LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

{% if "nvml_dev" in cuda.components %}
{% set nvml_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.nvml_dev.version %}
{% endif %}
{% if "command_line_tools" in cuda.components %}
{% set cmdline_tools_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.command_line_tools.version %}
{% endif %}
{% if "libcublas_dev" in cuda.components %}
{% set libcublas_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libcublas_dev.version %}
{% endif %}
{% if "libnccl2_dev" in cuda.components and cuda.components.libnccl2_dev %}
    {# {% set libnccl2_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libnccl2_dev.version %} #}
    {% if cuda.version.major | int >= 10 %}
        {% set libnccl2_dev_component_version = "%s+cuda%s.%s" | format(cuda.components.libnccl2_dev.version, cuda.version.major, cuda.version.minor) %}
    {% endif %}
{% endif %}
{% if "libraries_dev" in cuda.components %}
{% set libraries_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libraries_dev.version %}
{% endif %}
{% if "minimal_build" in cuda.components %}
{% set minimal_build_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.minimal_build.version %}
{% endif %}
{% if "libcusparse" in cuda.components %}
{% set libcusparse_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libcusparse.version %}
{% endif %}
{% if "libcusparse_dev" in cuda.components %}
{% set libcusparse_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libcusparse_dev.version -%}
{% endif %}
{% if "libnpp_dev" in cuda.components %}
    {% set libnpp_dev_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.libnpp_dev.version %}
{% endif -%}
{% if "nvprof" in cuda.components %}
    {% set nvprof_component_version = cuda.version.major + "-" + cuda.version.minor + "=" + cuda.components.nvprof.version %}
{% endif -%}
ENV NCCL_VERSION {{ cuda.components.libnccl2_dev.version[:-2] }}

RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-nvml-dev-{{ nvml_dev_component_version if nvml_dev_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    cuda-command-line-tools-{{ cmdline_tools_component_version if cmdline_tools_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    cuda-nvprof-{{ nvprof_component_version if nvprof_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    {% if (cuda.arch != "arm64" or cuda.arch == "ppc64le") and cuda.version.major | int <= 10 %}
    cuda-npp-dev-{{ libnpp_component_version if libnpp_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    {% else %}
    libnpp-dev-{{ libnpp_dev_component_version if libnpp_dev_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    {% endif %}
{% if cuda.version.major | int >= 9 and cuda.version.major | int >= 1 %}
    cuda-libraries-dev-{{ libraries_dev_component_version if libraries_dev_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
    cuda-minimal-build-{{ minimal_build_component_version if minimal_build_component_version and cuda.version.major | int >= 10 else "$CUDA_PKG_VERSION" }} \
{% endif %}
{% if cuda.version.major | int > 10 %}
    {# libnccl2_dev can be unset if libnccl2.source is being used #}
    {% if cuda.components.libnccl2_dev and not "source" in cuda.components.libnccl2 %}
    libnccl-dev={{ libnccl2_dev_component_version }} \
    {% endif %}
    libcublas-dev-{{ libcublas_dev_component_version if libcublas_dev_component_version and cuda.version.major | int >= 10 else "10.2." + cuda.version.minor + "." + cuda.version.build + "-1" }} \
    libcusparse-{{ libcusparse_component_version if libcusparse_component_version and cuda.version.major | int >= 10 else "10.2." + cuda.version.minor + "." + cuda.version.build + "-1" }} \
    libcusparse-dev-{{ libcusparse_dev_component_version if libcusparse_dev_component_version and cuda.version.major | int >= 10 else "10.2." + cuda.version.minor + "." + cuda.version.build + "-1" }} \
{% elif cuda.version.major | int == 10 %}
    {% set cublas_dev_vers = "%s.%s.%s.%s-1" | format(cuda.version.major, cuda.version.minor, cuda.version.minor, cuda.version.build) %}
    {% set haz10_2 = "-10-2" if cuda.arch == "arm64" and cuda.version.minor | int == 2 %}
    libcublas-dev{{ haz10_2 }}={{ cublas_dev_vers }} \
    libnccl-dev={{ libnccl2_dev_component_version }} \
{% endif %}
{% if cuda.version.major | int == 9 and cuda.version.minor | int == 0 %}
    cuda-core-{{ cuda.version.major }}-{{ cuda.version.minor }}={{ cuda.version.full }}.3-1 \
    cuda-cublas-dev-{{ cuda.version.major }}-{{ cuda.version.minor }}={{ cuda.version.full }}.4-1 \
{% elif cuda.version.major | int == 8 and cuda.version.minor | int == 0 %}
    cuda-core-$CUDA_PKG_VERSION \
    cuda-misc-headers-$CUDA_PKG_VERSION \
    cuda-nvrtc-dev-$CUDA_PKG_VERSION \
    cuda-nvgraph-dev-$CUDA_PKG_VERSION \
    cuda-cusolver-dev-$CUDA_PKG_VERSION \
    cuda-cublas-dev-8-0=8.0.61.2-1 \
    cuda-cufft-dev-$CUDA_PKG_VERSION \
    cuda-curand-dev-$CUDA_PKG_VERSION \
    cuda-cusparse-dev-$CUDA_PKG_VERSION \
    cuda-npp-dev-$CUDA_PKG_VERSION \
    cuda-cudart-dev-$CUDA_PKG_VERSION \
    cuda-driver-dev-$CUDA_PKG_VERSION \
{% endif %}
    {% if cuda.components.libnccl2_dev and not "source" in cuda.components.libnccl2 %}
    && apt-mark hold libnccl-dev \
    {% endif %}
    && rm -rf /var/lib/apt/lists/*

{% if "libnccl2" in cuda.components and "source" in cuda.components.libnccl2 %}
    {% set arch = cuda.arch %}
    {% if cuda.arch == "arm64" %} {% set arch = "aarch64" %} {% endif %}
    {% set basename =  "nccl_" + cuda.components.libnccl2.version + "-1+cuda" + cuda.version.major + "." + cuda.version.minor + "_" + arch + ".txz" %}
RUN apt update && apt install curl xz-utils -y --no-install-recommends && NCCL_DOWNLOAD_SUM={{ cuda.components.libnccl2.sha256sum }} && \
    curl -fsSL {{ cuda.components.libnccl2.source }} -O && \
    echo "$NCCL_DOWNLOAD_SUM  {{ basename }}" | sha256sum -c - && \
    tar --no-same-owner --keep-old-files --lzma -xvf  {{ basename }} -C /usr/local/cuda/include/ --strip-components=2 --wildcards '*/include/*' && \
    tar --no-same-owner --keep-old-files --lzma -xvf  {{ basename }} -C /usr/local/cuda/lib64/ --strip-components=2 --wildcards '*/lib/libnccl.so' && \
    rm {{ basename }} && \
    ldconfig && rm -rf /var/lib/apt/lists/*

{% endif %}
ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
